configs:
  asprice_dashboard_config:
    content: |
      {
        "Dashboard": {
          "TelemetryLimits": {
            "MaxLogCount": 100,
            "MaxTraceCount": 100,
            "MaxMetricsCount": 100
          },
          "Otlp": {
            "AuthMode": "ApiKey",
            "PrimaryApiKey": "9EFB07A6-E9F9-4AC1-A0DE-DBE829B7236B"
          }
        }
      }



services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - '18888:18888'
      - '18889:18889'
    configs:
      - source: asprice_dashboard_config
        target: /app/config_files/aspire-dashboard-config.json
    environment:
      - DOTNET_DASHBOARD_CONFIG_FILE_PATH=config_files/aspire-dashboard-config.json
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - type: bind
        source: ./azurite
        target: /data
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
#  postgres:
#    image: postgres:17.6
#    ports:
#      - '5432:5432'
#    volumes:
#      - type: bind
#        source: ./postgres
#        target: /var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=appuser
#      - POSTGRES_PASSWORD=Pl3@s3UseASt0ngP@ssw0rdN0tL!k3Th!s0n3
#      - POSTGRES_DB=binacle_net
#  minio:
#    image: minio/minio:latest
#    command: server /data --console-address ":9001"
#    ports:
#      - '9000:9000' # S3 API
#      - '9001:9001' # MinIO Console
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin123
#    volumes:
#      - type: bind
#        source: ./minio_data
#        target: /data
    
