name: Deploy Binacle.Net Web
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Binacle.Net Web
    runs-on: ubuntu-latest
    environment:
      name: binacle-net-web
      url: www.binacle.net
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app_name: 'binacle-net-web'


