############################################################
# Site settings
############################################################
title                   : "Binacle.Net"
description             : >-
  Binacle.Net is an API created to address the 3D Bin Packing Problem in real time.

author:
  name                  : "Chris Mavrommatis"
  url                   : "https://github.com/ChrisMavrommatis"
  
# the base hostname & protocol for your site, e.g. http://example.com# Welcome to Jekyll!
url                     : "https://www.binacle.net"

logo:
  src                  : /assets/logo/binacle-logo-512x512a.png
  alt                  : "Binacle.Net Logo"

gtm: 'GTM-N23CTC7C'

default_theme: "dark"

############################################################
# Where things are
############################################################
source              : ./
destination         : ../build/web
collections_dir     : collections
plugins_dir         : _plugins       # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
includes_dir        : _includes
data_dir            : _data
sass:
  sass_dir          : _sass
  cache             : false
  style             : compressed
collections:
  apps:
    output          : true
    permalink       : /app/:name/
  sitemaps:
    output          : true
    permalink       : /sitemap/:name:output_ext
    
############################################################
# Handling Reading
############################################################
safe                : false
include             :
  - ".htaccess"
exclude             :
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "*.proj"
  - "obj/*"
  - "bin/*"
  - "README.md"
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false
############################################################
# Filtering Content
############################################################
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

############################################################
# Serving
############################################################
detach              : false
port                : 7196
host                : 127.0.0.1
baseurl             : ""    # does not include hostname
show_dir_listing    : false
disable_disk_cache  : true

############################################################
# Conversion
############################################################
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

############################################################
# Outputting
############################################################
permalink           : date        #pretty
paginate_path       : /page:num
timezone            : "Europe/Athens"
quiet               : false
verbose             : false
liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

############################################################
# Markdown Processors
############################################################
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : '1..6'
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  parse_block_html  : true

############################################################
# Plugins
############################################################
whitelist           : []
plugins             :
  - jekyll-tidy

############################################################
# Front Matter Defaults
############################################################
defaults:
  - scope:
      path           : "pages/**"
      type           : "pages"
    values:
      layout          : "default"
      locale          : "en_US"
      hreflang        : "en"
      sitemap:
        lastmod       : "current"
        changefreq    : "monthly"
        priority      : 1.0
        exclude       : false
  - scope:
      path            : "**/**"
      type            : "apps"
    values:
      layout          : "default"
      title           : "NOTITLE"
      locale          : "en_US"
      hreflang        : "en"
      sitemap:
        lastmod       : "current"
        changefreq    : "monthly"
        priority      : 1.0
        exclude       : false
  - scope:
      path: "**/**"
      type: "sitemaps"
    values:
      title: "Sitemap"


############################################################
################### END OF BASE CONFIG #####################
############################################################


############################################################
# jekyll-tidy
############################################################
jekyll_tidy:
  exclude       : []       # an array of files to exclude from tidying.
  ignore_env    : null     # a JEKYLL_ENV string on which to skip tidying entirely.
  compress_html : false    # a flag for whether or not to compress the HTML output
